### ISSUE TITLE
Docker 도입

### ISSUE THREAD

**Issue by 5d-jh** [ssu-isteam/isteam#75]
## 현재 상황, 이로 인한 문제점
애플리케이션이 도커를 사용하지 않고 있음. 이로 인해 배포 과정이 복잡하며, 배포 환경을 재현하기 어려움.

## 개선 방안
도커파일을 사용하여 애플리케이션을 컨테이너화하여 배포함.

**Comment by yeop-sang** [comment]
## 필요사항 정리
- [ ] poetry 설치 과정
- [ ] css 빌드 과정
- [ ] django migrate 과정
- [ ] django runserver 과정

**Comment by yeop-sang** [comment]
그런데 혹시 poetry를 꼭 사용해야하는 이유가 있을까요?

현재 보니까 오히려 빌드를 해주는 bash를 만들고 venv를 poetry랑 별개로 생성하게 만들어 python 종속성을 분리하여서 docker내의 python 환경을 조성해주는 것이 더 좋아보입니다.

poetry에 대해서 다시 한 번 고려 봤으면 좋겠습니다
